/**
 *
 * $Id$
 */
package xml_model.model_xml.validation;

import org.eclipse.emf.common.util.EList;

import xml_model.model_xml.Attribute;
import xml_model.model_xml.Node;

/**
 * A sample validator interface for {@link xml_model.model_xml.Element}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementValidator {
	boolean validate();

	boolean validateValue(String value);

	boolean validateChildren(EList<Node> value);

	boolean validateAttributes(EList<Attribute> value);

	boolean validateRoot(boolean value);

	boolean validateAttribute(EList<Attribute> value);
}
